# Generated by Django 4.0.2 on 2022-05-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
