# Generated by Django 4.0.2 on 2022-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tomeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_for_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('month', models.CharField(choices=[('1', 'январь'), ('2', 'февраль'), ('3', 'март'), ('4', 'апрель'), ('5', 'май'), ('6', 'июнь'), ('7', 'июль'), ('8', 'август'), ('9', 'сентябрь'), ('10', 'октябрь'), ('11', 'ноябрь'), ('12', 'декабрь')], default='1', max_length=2)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('reason_for_goal', models.TextField()),
            ],
        ),
    ]
