# Generated by Django 4.0.2 on 2022-05-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_goal_for_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal_for_month',
        ),
        migrations.DeleteModel(
            name='ToMeet',
        ),
    ]
